IgCrm/urls.py
from django.contrib import admin
from django.urls import path,re_path, include

from app01 import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/',include('tinymce.urls') ),
    path('login/', views.login),
    path('get_valid_img/', views.get_valid_img),
    path('reg/', views.reg),
    path('logout/', views.logout),
    path('index/', views.index),
    path('', views.index),
    path('customers/list/', views.CustomerView.as_view(),name="customers_list"),
    path('mycustomers/', views.CustomerView.as_view(),name="mycustomers"),
    path('customer/add/', views.AddEditCustomerView.as_view(),name="addcustomers"),
    re_path('customer/edit/(\d+)', views.AddEditCustomerView.as_view(),name="editcustomers"),
    path('consult_records/', views.ConsultRecordView.as_view(),name="consult_records"),
    path('consult_records/add/', views.AddEditConsultRecordView.as_view(), name="add_consult_records"),
    re_path('consult_records/edit/(\d+)', views.AddEditConsultRecordView.as_view(), name="edit_consult_records"),
]

app01/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import AbstractUser
from tinymce.models import  HTMLField


from django.db import models
from django.contrib import auth
from django.core.exceptions import PermissionDenied
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager, User
from django.utils.translation import ugettext_lazy as _
from multiselectfield import MultiSelectField
from django.utils.safestring import mark_safe

course_choices = (('LinuxL', 'Linux中高级'),
                  ('PythonFullStack', 'Python高级全栈开发'),)

class_type_choices = (('fulltime', '脱产班',),
                      ('online', '网络班'),
                      ('weekend', '周末班',),)

source_type = (('qq', "qq群"),
               ('referral', "内部转介绍"),
               ('website', "官方网站"),
               ('baidu_ads', "百度推广"),
               ('office_direct', "直接上门"),
               ('WoM', "口碑"),
               ('public_class', "公开课"),
               ('website_luffy', "路飞官网"),
               ('others', "其它"),)

enroll_status_choices = (('signed', "已报名"),
                         ('unregistered', "未报名"),
                         ('studying', '学习中'),
                         ('paid_in_full', "学费已交齐"))

seek_status_choices = (('A', '近期无报名计划'), ('B', '1个月内报名'), ('C', '2周内报名'), ('D', '1周内报名'),
                       ('E', '定金'), ('F', '到班'), ('G', '全款'), ('H', '无效'),)
pay_type_choices = (('deposit', "订金/报名费"),
                    ('tuition', "学费"),
                    ('transfer', "转班"),
                    ('dropout', "退学"),
                    ('refund', "退款"),)

attendance_choices = (('checked', "已签到"),
                      ('vacate', "请假"),
                      ('late', "迟到"),
                      ('absence', "缺勤"),
                      ('leave_early', "早退"),)

score_choices = ((100, 'A+'),
                 (90, 'A'),
                 (85, 'B+'),
                 (80, 'B'),
                 (70, 'B-'),
                 (60, 'C+'),
                 (50, 'C'),
                 (40, 'C-'),
                 (0, ' D'),
                 (-1, 'N/A'),
                 (-100, 'COPY'),
                 (-1000, 'FAIL'),)


class UserInfo(AbstractUser):
    """
    员工表
    """
    tel=models.CharField(max_length=32,null=True,blank=True)
    gender=models.IntegerField(choices=((1,"男"),(2,"女")),default=1)
    # depart=models.ForeignKey("Department",on_delete=models.CASCADE,default=1)

class Department(models.Model):
    """
    部门表
    """
    name=models.CharField(max_length=32)
    count=models.IntegerField()


class Customer(models.Model):
    """
    客户表
    """
    qq = models.CharField('QQ', max_length=64, unique=True, help_text='QQ号必须唯一')
    qq_name = models.CharField('QQ昵称', max_length=64, blank=True, null=True)
    name = models.CharField('姓名', max_length=32, blank=True, null=True, help_text='学员报名后，请改为真实姓名',default="")
    sex_type = (('male', '男'), ('female', '女'))
    sex = models.CharField("性别", choices=sex_type, max_length=16, default='male', blank=True, null=True)
    birthday = models.DateField('出生日期', default=None, help_text="格式yyyy-mm-dd", blank=True, null=True)
    phone = models.BigIntegerField('手机号', blank=True, null=True)
    source = models.CharField('客户来源', max_length=64, choices=source_type, default='qq')
    introduce_from = models.ForeignKey('Customer', verbose_name="转介绍自学员", blank=True, null=True,on_delete=models.CASCADE)
    course = MultiSelectField("咨询课程", choices=course_choices,null=True,blank=True)
    class_type = models.CharField("班级类型", max_length=64, choices=class_type_choices, default='fulltime')
    customer_note = models.TextField("客户备注", blank=True, null=True, )
    status = models.CharField("状态", choices=enroll_status_choices, max_length=64, default="unregistered",
                              help_text="选择客户此时的状态")
    date = models.DateTimeField("咨询日期", auto_now_add=True)
    last_consult_date = models.DateField("最后跟进日期", auto_now_add=True)
    next_date = models.DateField("预计再次跟进时间", blank=True, null=True)
    consultant = models.ForeignKey('UserInfo', verbose_name="销售", related_name='customers', blank=True, null=True,on_delete=models.CASCADE )
    class_list = models.ManyToManyField('ClassList', verbose_name="已报班级",null=True,blank=True)

    def __str__(self):
        return self.name+":"+self.qq


    def get_classlist(self):
        l=[]
        for cls in self.class_list.all():
            l.append(str(cls))
        return mark_safe("<br>".join(l))

    def get_status(self):
        status_color={
            "studying":"green",
            "signed":"#B03060",
            "unregistered":"red",
            "paid_in_full":"blue"
        }
        return mark_safe("<span style='background-color:%s;color:white'>%s</span>"%(status_color[self.status],self.get_status_display()))




class Campuses(models.Model):
    """
    校区表
    """
    name = models.CharField(verbose_name='校区', max_length=64)
    address = models.CharField(verbose_name='详细地址', max_length=512, blank=True, null=True)

    def __str__(self):
        return self.name


class ClassList(models.Model):
    """
    班级表
    """
    course = models.CharField("课程名称", max_length=64, choices=course_choices)
    semester = models.IntegerField("学期")
    campuses = models.ForeignKey('Campuses', verbose_name="校区",on_delete=models.CASCADE)
    price = models.IntegerField("学费", default=10000)
    memo = models.CharField('说明', blank=True, null=True, max_length=100)
    start_date = models.DateField("开班日期")
    graduate_date = models.DateField("结业日期", blank=True, null=True)
    #contract = models.ForeignKey('ContractTemplate', verbose_name="选择合同模版", blank=True, null=True,on_delete=models.CASCADE)
    teachers = models.ManyToManyField('UserInfo', verbose_name="老师")
    class_type = models.CharField(choices=class_type_choices, max_length=64, verbose_name='班额及类型', blank=True,
                                  null=True)

    class Meta:
        unique_together = ("course", "semester", 'campuses')

    def __str__(self):
        return "{}{}({})".format(self.get_course_display(), self.semester, self.campuses)



class ConsultRecord(models.Model):
    """
    跟进记录表
    """
    customer = models.ForeignKey('Customer', verbose_name="所咨询客户",on_delete=models.CASCADE)
    note = HTMLField(verbose_name="跟进内容...")
    status = models.CharField("跟进状态", max_length=8, choices=seek_status_choices, help_text="选择客户此时的状态")
    consultant = models.ForeignKey("UserInfo", verbose_name="跟进人", related_name='records',on_delete=models.CASCADE)
    date = models.DateTimeField("跟进日期", auto_now_add=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)
    def __str__(self):
        return str(self.customer)+str(self.consultant)



class Enrollment(models.Model):
    """
    报名表
    """
    customer = models.ForeignKey('Customer', verbose_name='客户名称',on_delete=models.CASCADE)
    why_us = models.TextField("为什么报名", max_length=1024, default=None, blank=True, null=True)
    your_expectation = models.TextField("学完想达到的具体期望", max_length=1024, blank=True, null=True)
    enrolled_date = models.DateTimeField(auto_now_add=True, verbose_name="报名日期")
    memo = models.TextField('备注', blank=True, null=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)
    school = models.ForeignKey('Campuses',on_delete=models.CASCADE)
    enrolment_class = models.ForeignKey("ClassList", verbose_name="所报班级",on_delete=models.CASCADE)

    class Meta:
        unique_together = ('enrolment_class', 'customer')


class PaymentRecord(models.Model):
    """
    缴费记录表
    """
    customer = models.ForeignKey('Customer', verbose_name="客户",on_delete=models.CASCADE)
    pay_type = models.CharField("费用类型", choices=pay_type_choices, max_length=64, default="deposit")
    paid_fee = models.IntegerField("费用数额", default=0)
    note = models.TextField("备注", blank=True, null=True)
    date = models.DateTimeField("交款日期", auto_now_add=True)
    course = models.CharField("课程名", choices=course_choices, max_length=64, blank=True, null=True, default='N/A')
    class_type = models.CharField("班级类型", choices=class_type_choices, max_length=64, blank=True, null=True,
                                  default='N/A')
    enrolment_class = models.ForeignKey('ClassList', verbose_name='所报班级', blank=True, null=True,on_delete=models.CASCADE)
    consultant = models.ForeignKey('UserInfo', verbose_name="销售",on_delete=models.CASCADE)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)

    status_choices = (
        (1, '未审核'),
        (2, '已审核'),
    )
    status = models.IntegerField(verbose_name='审核', default=1, choices=status_choices)

    confirm_date = models.DateTimeField(verbose_name="确认日期", null=True, blank=True)
    confirm_user = models.ForeignKey(verbose_name="确认人", to='UserInfo', related_name='confirms', null=True,
                                     blank=True,on_delete=models.CASCADE)

#############################################################


# class CourseRecord(models.Model):
#     """课程记录表"""
#     day_num = models.IntegerField("节次", help_text="此处填写第几节课或第几天课程...,必须为数字")
#     date = models.DateField(auto_now_add=True, verbose_name="上课日期")
#     course_title = models.CharField('本节课程标题', max_length=64, blank=True, null=True)
#     course_memo = models.TextField('本节课程内容', max_length=300, blank=True, null=True)
#     has_homework = models.BooleanField(default=True, verbose_name="本节有作业")
#     homework_title = models.CharField('本节作业标题', max_length=64, blank=True, null=True)
#     homework_memo = models.TextField('作业描述', max_length=500, blank=True, null=True)
#     scoring_point = models.TextField('得分点', max_length=300, blank=True, null=True)
#     re_class = models.ForeignKey('ClassList', verbose_name="班级")
#     teacher = models.ForeignKey('UserProfile', verbose_name="讲师")
#
#     class Meta:
#         unique_together = ('re_class', 'day_num')
#
#
# class StudyRecord(models.Model):

templates/add_customer.html
{% extends 'base.html'%}


{% block content %}
    <div class="content-wrapper">
          <!-- Content Header (Page header) -->
          <section class="content-header">
              <h1>添加客户
                  <small>Optional description</small>
              </h1>
              <ol class="breadcrumb">
                  <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
                  <li class="active">Here</li>
              </ol>
          </section>

          <!-- Main content -->
          <section class="content">

            <div class="row">
                  <div class="col-md-8 col-md-offset-2">
                      <form action="" method="post" novalidate>
                        {% csrf_token %}
                        {% for field in form %}
                         <div class="form-group">
                             <label for="">{{ field.label }}</label>
                            {{ field }}
                            <span class="error">{{ field.errors.0 }}</span>
                         </div>
                         {% endfor %}
                        <button class="btn btn-default">提交</button>
                     </form>
                  </div>
            </div>

          </section>
          <!-- /.content -->
      </div>
{% endblock %}

templates/add_edit_consultrecord.html
{% extends 'base.html'%}


{% block content %}
    <div class="content-wrapper">
          <!-- Content Header (Page header) -->
          <section class="content-header">
              <h1>
                  {% if edit_obj %}
                  编辑跟进记录
                  {% else %}
                  添加跟进记录
                  {% endif %}

                  <small>Optional description</small>
              </h1>
              <ol class="breadcrumb">
                  <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
                  <li class="active">Here</li>
              </ol>
          </section>

          <!-- Main content -->
          <section class="content">

            <div class="row">
                  <div class="col-md-8 col-md-offset-2">
                      <form action="" method="post" novalidate>
                        {% csrf_token %}
                        {% for field in form %}
                         <div class="form-group">
                             <label for="">{{ field.label }}</label>
                            {{ field }}
                            <span class="error">{{ field.errors.0 }}</span>
                         </div>
                         {% endfor %}
                        <button class="btn btn-default">提交</button>
                     </form>
                  </div>
            </div>

          </section>
          <!-- /.content -->
      </div>
{% endblock %}

templates/add_edit_customer.html
{% extends 'base.html'%}


{% block content %}
    <div class="content-wrapper">
          <!-- Content Header (Page header) -->
          <section class="content-header">
              <h1>
                  {% if edit_obj %}
                  编辑用户
                  {% else %}
                  添加客户
                  {% endif %}

                  <small>Optional description</small>
              </h1>
              <ol class="breadcrumb">
                  <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
                  <li class="active">Here</li>
              </ol>
          </section>

          <!-- Main content -->
          <section class="content">

            <div class="row">
                  <div class="col-md-8 col-md-offset-2">
                      <form action="" method="post" novalidate>
                        {% csrf_token %}
                        {% for field in form %}
                         <div class="form-group">
                             <label for="">{{ field.label }}</label>
                            {{ field }}
                            <span class="error">{{ field.errors.0 }}</span>
                         </div>
                         {% endfor %}
                        <button class="btn btn-default">提交</button>
                     </form>
                  </div>
            </div>

          </section>
          <!-- /.content -->
      </div>
{% endblock %}

templates/consultrecord.html
{% extends "base.html" %}



{% block content %}
     <div class="content-wrapper small">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h3>
                跟进记录详情
                <small>Optional description</small>
            </h3>
            <!-- 模糊查询的form表单  -->




        </section>

       <!-- action批量处理的form表单  -->


            <!-- Main content -->
            <section class="content">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="box">
                            <div class="box-header">
                                <h3 class="box-title"><a href="{% url 'add_consult_records' %}" class="btn btn-primary btn-sm">添加跟进记录</a></h3>
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body">
                                <table  id="example2" class="text-center table table-bordered table-hover">
                                    <thead>
                                        <tr>

                                            <th>编号</th>
                                            <th>客户姓名</th>
                                            <th>当前状态</th>
                                            <th>内容</th>
                                            <th>销售</th>
                                            <th>操作</th>
                                        </tr>
                                    </thead>
                                    <tbody>

                                     {% for consult_record in consult_record_list %}
                                         <tr>
                                              <td>{{ forloop.counter }}</td>
                                              <td>{{ consult_record.customer.name }}</td>
                                              <td>{{ consult_record.customer.get_status }}</td>
                                              <td>{{ consult_record.note }}</td>
                                              <td>{{ consult_record.consultant|default:"暂无" }}</td>
                                              <td>
                                                  <a href="" class="btn btn-warning btn-sm">编辑</a>
                                                  <a href="" class="btn btn-danger btn-sm">删除</a>
                                              </td>

                                         </tr>
                                     {% endfor %}


                                    </tbody>
                                </table>
                                <nav aria-label="Page navigation" class="pull-right">
                                      <ul class="pagination">
                                         {{ pagination.page_html|safe }}
                                      </ul>
                                </nav>
                            </div>
                            <!-- /.box-body -->
                        </div>
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </section>
            <!-- /.content -->


    </div>

{% endblock %}

templates/customer_list.html
{% extends "base.html" %}


{% block content %}
    <div class="content-wrapper small">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h3>
                {{ label }}
                <small>Optional description</small>
            </h3>
            <!-- 模糊查询的form表单  -->
             <form action="" method="get" class="pull-right">
                 <ol class="breadcrumb">
                    <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
                    <li class="active">Here</li>
                     <select name="field" id="s1" class="form-control" style="display: inline-block;width: 100px">
                         <option value="name">姓名</option>
                         <option value="qq">qq</option>
                         <option value="phone">手机</option>
                         <option value="status">状态</option>
                     </select>
                    <input class="form-control" style="display: inline-block;width: 200px" type="text" name="q">
                    <button style="vertical-align: 0px" class="btn btn-success">search</button>
                </ol>
            </form>



        </section>

       <!-- action批量处理的form表单  -->
      <form action="" method="post">
            {% csrf_token %}
            <ol class="breadcrumb">
                     <select name="action" id="" class="form-control" style="display: inline-block;width: 240px">
                         <option value="patch_delete">请选择批量处理方法</option>
                         <option value="patch_delete">delete selected data</option>
                         <option value="patch_reverse_gs">公户转私户</option>
                         <option value="patch_reverse_sg">私户转公户</option>
                     </select>
                    <button style="vertical-align: 0px" class="btn btn-danger">go</button>
            </ol>

            <!-- Main content -->
            <section class="content">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="box">
                            <div class="box-header">
                                <h3 class="box-title"><a href="/customer/add/{{ next }}" class="btn btn-primary btn-sm">添加客户</a></h3>
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body">
                                <table  id="example2" class="text-center table table-bordered table-hover">
                                    <thead>
                                        <tr>
                                            <th><input type="checkbox"></th>
                                            <th>编号</th>
                                            <th>客户姓名</th>
                                            <th>性别</th>
                                            <th>QQ</th>
                                            <th>手机号</th>
                                            <th>客户来源</th>
                                            <th>咨询日期</th>
                                            <th>当前状态</th>
                                            <th>销售</th>
                                            <th>所报班级</th>
                                            <th>跟进记录</th>
                                            <th>编辑</th>
                                            <th>删除</th>
                                        </tr>
                                    </thead>
                                    <tbody>

                                     {% for customer in customer_list %}
                                         <tr>
                                              <td><input type="checkbox" name="selected_pk_list" value="{{ customer.pk }}"></td>
                                              <td>{{ forloop.counter }}</td>
                                              <td>{{ customer.name }}</td>
                                              <td>{{ customer.get_sex_display }}</td>
                                              <td>{{ customer.qq }}</td>
                                              <td>{{ customer.phone }}</td>
                                              <td>{{ customer.get_source_display }}</td>
                                              <td>{{ customer.date|date:'Y-m-d' }}</td>
                                              <td>{{ customer.get_status }}</td>
                                              <td>{{ customer.consultant|default:"暂无" }}</td>
                                              <td>{{ customer.get_classlist|default:"暂无" }}</td>
                                              <td><a href="/consult_records/?customer_id={{ customer.pk }}">跟进详情</a></td>
                                              <td>
                                                  {{ next }}
                                                  <a href="{% url 'editcustomers' customer.pk %}{{ next }}"><i class="fa fa-edit" aria-hidden="true"></i></a>
                                              </td>
                                              <td>
                                                  <a href=""><i class="fa fa-trash-o fa-lg"></i></a>

                                              </td>

                                         </tr>
                                     {% endfor %}


                                    </tbody>
                                </table>
                                <nav aria-label="Page navigation" class="pull-right">
                                      <ul class="pagination">
                                         {{ pagination.page_html|safe }}
                                      </ul>
                                </nav>
                            </div>
                            <!-- /.box-body -->
                        </div>
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </section>
            <!-- /.content -->

      </form>
    </div>


{% endblock %}


{% block js %}
   <script>
                   $("#s1").change(function () {
                       if($(this).val()==="status"){
                             let s1=`
                             <select name="q" id="s2" class="form-control" style="display: inline-block;width: 100px">
                                 <option value="signed">已报名</option>
                                 <option value="unregistered">未报名</option>
                                 <option value="studying">学习中</option>
                                 <option value="paid_in_full">学费已交齐</option>
                             </select>
                             `;

                           $(this).next().replaceWith(s1)
                       }
                   })
            </script>
{% endblock %}

templates/edit_customer.html
{% extends 'base.html'%}


{% block content %}
    <div class="content-wrapper">
          <!-- Content Header (Page header) -->
          <section class="content-header">
              <h1>编辑客户
                  <small>Optional description</small>
              </h1>
              <ol class="breadcrumb">
                  <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
                  <li class="active">Here</li>
              </ol>
          </section>

          <!-- Main content -->
          <section class="content">

            <div class="row">
                  <div class="col-md-8 col-md-offset-2">
                      <form action="" method="post" novalidate>
                        {% csrf_token %}
                        {% for field in form %}
                         <div class="form-group">
                             <label for="">{{ field.label }}</label>
                            {{ field }}
                            <span class="error">{{ field.errors.0 }}</span>
                         </div>
                         {% endfor %}
                        <button class="btn btn-default">提交</button>
                     </form>
                  </div>
            </div>

          </section>
          <!-- /.content -->
      </div>
{% endblock %}

templates/index.html
{% extends "base.html" %}

templates/login.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.css">
</head>
<body>
<h3>登录页面</h3>

<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <form action="" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="">用户名</label>
                    <input type="text" class="form-control" id="user">
                </div>
                 <div class="form-group">
                    <label for="">密码</label>
                    <input type="password" class="form-control" id="pwd">
                </div>
                <div class="form-group">
                    <label for="">验证码</label>
                    <div class="row">
                       <div class="col-md-6">
                            <input type="text" class="form-control" id="validcode">
                       </div>
                       <div class="col-md-6">
                           <img width="350" height="38" src="/get_valid_img/" alt="" id="img">
                       </div>
                    </div>

                </div>


                <input type="button" class="btn btn-primary pull-right login_btn" value="登录">
                <span class="error"></span>
            </form>
        </div>
    </div>
</div>


<script src="/static/js/jquery.js"></script>
<script>


     $(".login_btn").click(function () {


         $.ajax({
             url:"",
             type:"post",
             data:{
                 user:$("#user").val(),
                 pwd:$("#pwd").val(),
                 validcode:$("#validcode").val(),
                 csrfmiddlewaretoken:$("[name='csrfmiddlewaretoken']").val()
             },
             success:function (response) {
                     console.log(response);

                     if(response.user){
                         // 登录成功
                         if(location.search.slice(6)){
                             location.href=location.search.slice(6)
                         }
                         else{
                             location.href="/"
                         }
                     }
                     else{
                         // 登录失败
                         $(".error").html(response.err_msg).css("color","red")
                     }
             }
         })


     })

    //  验证码刷新
    $("#img").click(function () {
        this.src+="?"
    })

</script>
</body>
</html>

templates/reg.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.css">
</head>
<body>
<h3>注册页面</h3>

<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <form action="" method="post">
                {% csrf_token %}

                {% for field in form %}
                       <div class="form-group">
                            <label for="">{{ field.label }}</label>
                            {{ field }}
                            <span class="error pull-right"></span>
                        </div>
                {% endfor %}



                <input type="button" class="btn btn-primary reg_btn" value="注册">
            </form>
        </div>
    </div>
</div>


<script src="/static/js/jquery.js"></script>
<script>

    $(".reg_btn").click(function () {


        $.ajax({
            url:"",
            type:"post",
            data:{
                user:$("#id_user").val(),
                pwd:$("#id_pwd").val(),
                gender:$("#id_gender").val(),
                r_pwd:$("#id_r_pwd").val(),
                email:$("#id_email").val(),
                csrfmiddlewaretoken:$("[name='csrfmiddlewaretoken']").val()

            },
            success:function (res) {
                console.log(res);

                if (res.user){
                    // 注册成功
                    location.href="/login/"
                }
                else{

                 // 清除错误
                $(".error").html("");
                $(".form-group").removeClass("has-error");

                //  展示新的错误
                $.each(res.err_msg,function (i,j) {
                    console.log(i,j);

                    $("#id_"+i).next().html(j[0]).css("color","red").parent().addClass("has-error")



                })


                }



            }
        })



    })


</script>
</body>
</html>